require:
 - rubocop-rails
 - rubocop-capybara

AllCops:
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - "test/models/rush_job_mongoid/*.rb"
    - "test/system/rush_job_mongoid/*.rb"

Gemspec/RequiredRubyVersion:
  Enabled: false